### PR TITLE
Kira 1.1 and EOS error

### PR DESCRIPTION
**Pull request by raydsameshima**
Updated version Kira 1.1, and fixed EOS error.

### CODE REVIEW

**Comment by tueda** [comment]
Thanks for your PR! Would you mind squash the commits into one (or maybe two: kira 1.1 and fixing EOS)? Or may I do that?

**Comment by tueda** [comment]
You can edit the commit history in your local repository with `git rebase -i ...` and then update your public repository by `git push origin kira1-1 --force`.

**Comment by raydsameshima** [comment]
As you can see in my commit log, I've tried to separate my commits but I was not able to manage.
If you do not mind, could you please separate these as

1.  fixed EOS error
2.  updated for kira1.1 ?

**Comment by tueda** [comment]
I guess what you wanted to create was two commits https://github.com/tueda/homebrew-loops/pull/9/commits/85ff7eca150da946d74a681920b55cbe7a224347 for kira 1.1 and https://github.com/tueda/homebrew-loops/pull/9/commits/470e6d30b9642b4a9f2cb3a19034d7000db40ece for `<<~EOS`. The 1st commit looks the same as the 4th and the 2nd looks like 5th.

If this is correct, I would cherry-pick the 4th and 5th commits instead of merging all of them, and ignore from the 1st to 3rd. Is it OK for you?

**Comment by raydsameshima** [comment]
Absolutely!
Initially I've applied <<~EOS for kira1.0, and then updated kira1.1.
So 1st and 3rd are the same, 2nd and 4th are also.

**Comment by tueda** [comment]
I have added your two commits. Thanks for your contribution!

**Pull request closed without merging**
