### PR TITLE
kira 1.2, checked on Ubuntu18.04

### PR DESCRIPTION
**Pull request by raydsameshima**
Dear Ueda-san,

Sorry for the previous PR, but now it works.
I've updated for kira 1.2.

### CODE REVIEW

**Comment by tueda** [comment]
Hi Sameshima-san. Thanks for your PR!

Still Kira 1.2 seems to be in a beta test (Kira 1.2 beta 2018-07-17). I think what we need is [creating `head`](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#head), which is for the `--HEAD` option of `brew install` that allows users to install the latest version in a development repository. Perhaps you have tried for that, by adding `head`. To add dependencies only for `--HEAD` builds, you can write it like
```
head do
  url "https://gitlab.com/kira-pyred/kira.git"
  depends_on "autoconf" => :build
  depends_on "automake" => :build
end
```

I would suggest that `desc`, ..., `sha256` should be reverted and remain for Kira 1.1 (I don't know if they will change the official website), and we add `head`. The command `system "autoreconf", "-i"` (not `system "autoreconf -i"`, for which Rubocop complained on Travis CI) should be executed only for a build with `--HEAD`, i.e., with a conditional modifier `if build.head?`. Maybe the [`form` formula](https://github.com/tueda/homebrew-form/blob/master/form.rb) would be useful to get a rough idea of how to work with the `--HEAD` option.

You can also add the following line in `.travis.yml`
```
  - PACKAGE=kira OPTIONS=--HEAD
```
at the last section (probably just after the line of `- PACKAGE=kira`) to make the `--HEAD` build be tested on Travis CI. If you are not sure, I can do this change for Travis. For now the Travis test fails for all packages using Fortran, which should be repaired somehow.

**Comment by raydsameshima** [comment]
Ueda-san,

As you suggested, I've used head option.
So far I've tested both 1.1 with no option, and 1.2 with --HEAD.
(Still the Travis CI complains something, but I do not know anything on this side.)

**Comment by tueda** [comment]
OK. I think the URL for the Git repository is better, rather than the specific tarball for the master branch with sha256. It will be broken sooner or later when they make an update. And kira now manually specifies `-std=c++14`:
https://gitlab.com/kira-pyred/kira/blob/d6a0855ed927407cc5070b6514bedf8df032e82b/src/Makefile.am#L2
 which doesn't work for gcc 4.8 (which implements `-std=c++1y`). So you can write
```
  head do
    url "https://gitlab.com/kira-pyred/kira.git"
    depends_on "autoconf" => :build
    depends_on "automake" => :build
    needs :cxx14
  end
```
For the Rubocop error on Travis, I need to investigate. It should work...

**Comment by raydsameshima** [comment]
Dear Ueda-san,

I've modified as you wrote, thank you.

**Comment by tueda** [comment]
It seems that `needs :cxx14` is just for rejecting old compilers and doesn't install new gcc automatically.

**Comment by tueda** [comment]
Your changes look quite reasonable, though somehow tests on Travis CI have problems. For now I merge your PR and try to see what I can do for Travis. Thanks!

**Pull request merged**
